import type { Metadata } from 'next'
import Link from 'next/link'
import Nav from '@/components/Nav'

export const metadata: Metadata = { title: 'Terms of Service — Forcapedia' }

const LAST_UPDATED = 'February 22, 2026'

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main style={{ minHeight: '100vh', paddingTop: '64px', paddingBottom: '6rem' }}>
        <div style={{ maxWidth: '720px', margin: '0 auto', padding: '4rem 1.5rem 0' }}>

          {/* Header */}
          <p style={{
            fontFamily: 'var(--font-mono)', fontSize: '10px', letterSpacing: '0.12em',
            textTransform: 'uppercase', color: 'var(--gold)', marginBottom: '1rem',
          }}>
            Legal
          </p>
          <h1 style={{
            fontFamily: 'var(--font-serif)', fontSize: 'clamp(2rem, 5vw, 3rem)',
            fontWeight: 300, color: 'var(--text-primary)', marginBottom: '0.5rem', lineHeight: 1.1,
          }}>
            Terms of Service
          </h1>
          <p style={{
            fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text-tertiary)',
            marginBottom: '3rem',
          }}>
            Last updated: {LAST_UPDATED}
          </p>

          <div className="article-prose">

            <p>
              By accessing or using Forcapedia ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service.
            </p>

            <h2>1. The Service</h2>
            <p>
              Forcapedia is an AI-powered knowledge platform that generates verified, encyclopedic articles
              on demand. Articles are generated using large language models and carry a verification timestamp
              indicating when the content was produced. All content is AI-generated and should not be used
              as a sole source for critical decisions.
            </p>

            <h2>2. Accounts</h2>
            <p>
              You must sign in using a valid Google account to use the search and follow-up features.
              You are responsible for maintaining the security of your account. We do not store passwords —
              authentication is handled entirely by Google OAuth 2.0.
            </p>
            <p>
              You must be at least 13 years old to use Forcapedia. By signing in, you confirm you meet
              this requirement.
            </p>

            <h2>3. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service to generate illegal, harmful, or deceptive content</li>
              <li>Attempt to circumvent token limits, rate limits, or access controls</li>
              <li>Use automated scripts or bots to mass-generate articles</li>
              <li>Resell, redistribute, or sublicense access to the Service</li>
              <li>Attempt to extract, reverse-engineer, or scrape our AI systems</li>
              <li>Impersonate other users or create multiple accounts to circumvent limits</li>
            </ul>
            <p>
              Violation of these terms may result in immediate account termination without refund.
            </p>

            <h2>4. Token Limits & Tiers</h2>
            <p>
              Each plan includes a monthly token allocation. Tokens reset on the first day of each calendar
              month. Unused tokens do not carry over. If you reach your limit, searches will be paused
              until your next billing cycle or until you upgrade.
            </p>
            <p>
              Free tier users receive 50,000 tokens per month. Paid tiers receive significantly higher
              allocations as described on the <Link href="/pricing" style={{ color: 'var(--gold)' }}>Pricing page</Link>.
            </p>

            <h2>5. AI-Generated Content Disclaimer</h2>
            <p>
              All articles on Forcapedia are generated by AI language models. While we strive for
              accuracy, AI systems can produce errors, outdated information, or plausible-sounding
              inaccuracies. The "verified at" timestamp reflects when the article was generated,
              not independent fact-checking.
            </p>
            <p>
              Do not rely on Forcapedia content for medical, legal, financial, or safety-critical decisions
              without independent verification from qualified professionals.
            </p>

            <h2>6. Intellectual Property</h2>
            <p>
              The Forcapedia name, logo, and platform design are proprietary. AI-generated article content
              produced through your searches is provided for your personal, non-commercial use. You may
              not republish, sell, or distribute article content at scale without written permission.
            </p>

            <h2>7. Payments & Refunds</h2>
            <p>
              Paid subscriptions are billed monthly. You may cancel at any time — cancellation takes
              effect at the end of your current billing period. We do not offer prorated refunds for
              unused portions of a billing period. For billing issues, contact us at the address below.
            </p>

            <h2>8. Service Availability</h2>
            <p>
              We aim for high availability but do not guarantee uninterrupted access. We may modify,
              suspend, or discontinue features at any time. We will make reasonable efforts to notify
              users of significant changes.
            </p>

            <h2>9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Forcapedia and its operators shall not be liable
              for any indirect, incidental, special, or consequential damages arising from your use of
              the Service, including reliance on AI-generated content.
            </p>

            <h2>10. Governing Law</h2>
            <p>
              These Terms are governed by applicable law. Any disputes shall be resolved through
              good-faith negotiation before pursuing legal remedies.
            </p>

            <h2>11. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. Continued use of the Service after changes are
              posted constitutes acceptance of the new Terms. The "Last updated" date at the top of
              this page reflects the most recent revision.
            </p>

            <h2>12. Contact</h2>
            <p>
              For questions about these Terms, please reach out via the contact information available
              on our platform. For account deletion requests, visit your{' '}
              <Link href="/profile" style={{ color: 'var(--gold)' }}>Account settings</Link>.
            </p>

          </div>

          {/* Footer nav */}
          <div style={{
            marginTop: '3rem', paddingTop: '2rem', borderTop: '1px solid var(--border)',
            display: 'flex', gap: '1.5rem', flexWrap: 'wrap',
          }}>
            <Link href="/privacy" style={{
              fontFamily: 'var(--font-mono)', fontSize: '11px', letterSpacing: '0.05em',
              textTransform: 'uppercase', color: 'var(--text-tertiary)', textDecoration: 'none',
            }}>
              Privacy Policy
            </Link>
            <Link href="/pricing" style={{
              fontFamily: 'var(--font-mono)', fontSize: '11px', letterSpacing: '0.05em',
              textTransform: 'uppercase', color: 'var(--text-tertiary)', textDecoration: 'none',
            }}>
              Pricing
            </Link>
            <Link href="/" style={{
              fontFamily: 'var(--font-mono)', fontSize: '11px', letterSpacing: '0.05em',
              textTransform: 'uppercase', color: 'var(--text-tertiary)', textDecoration: 'none',
            }}>
              ← Home
            </Link>
          </div>

        </div>
      </main>
    </>
  )
}
